//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RomanCalculator.UnitTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RomanCalculator.UnitTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1|I
        ///2|II
        ///3|III
        ///4|IV
        ///5|V
        ///6|VI
        ///7|VII
        ///8|VIII
        ///9|IX
        ///10|X
        ///11|XI
        ///12|XII
        ///13|XIII
        ///14|XIV
        ///15|XV
        ///16|XVI
        ///17|XVII
        ///18|XVIII
        ///19|XIX
        ///20|XX
        ///21|XXI
        ///22|XXII
        ///23|XXIII
        ///24|XXIV
        ///25|XXV
        ///26|XXVI
        ///27|XXVII
        ///28|XXVIII
        ///29|XXIX
        ///30|XXX
        ///31|XXXI
        ///32|XXXII
        ///33|XXXIII
        ///34|XXXIV
        ///35|XXXV
        ///36|XXXVI
        ///37|XXXVII
        ///38|XXXVIII
        ///39|XXXIX
        ///40|XL
        ///41|XLI
        ///42|XLII
        ///43|XLIII
        ///44|XLIV
        ///45|XLV
        ///46|XLVI
        ///47|XLVII
        ///48|XLVIII
        ///49|XLIX
        ///50|L
        ///51|LI
        ///52|LII
        ///53|LIII
        ///54|LIV
        ///55|LV
        ///56|LVI
        ///57|LVII
        ///58|LVIII
        ///59|LIX
        ///60|LX
        ///61|LXI
        ///6 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UnitTests_ListOfRomanNumbers {
            get {
                return ResourceManager.GetString("UnitTests_ListOfRomanNumbers", resourceCulture);
            }
        }
    }
}
